# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    #- run: npm start
    - run: npm test
    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      uses: docker/login-action@v2.2.0
      with:
        username: ${{secrets.DOCKER_HUB_USERNAME}}
        password: ${{secrets.DOCKER_HUB_PASSWORD}}
    - run: ls
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.1.1
      with:
       # file: Dockerfile
        context: .
        push: true
        tags: ${{secrets.DOCKER_HUB_USERNAME}}/ga-nodejs:latest